{ ... }:
{
  imports = [
    ./hyprland
    ./ags
    ./wallpaper
    ./clipboard-manager
    ./rofi
    ./browser
    ./file-manager
    ./disk-manager
    ./text-editor
    ./system-monitor
    ./camera
    ./clock
    ./image-viewer
    ./video-player
    ./audio-player
    ./document-viewer
    ./document-scanner
    ./ebook-reader
    ./screenshot
    ./calendar
    ./calculator
    ./characters
    ./email
    ./voice-control
  ];
}
